version: "2"
linters:
  default: standard
  enable:
    - bidichk
    - errcheck
    - bodyclose
    - canonicalheader
    - copyloopvar
    - cyclop
    - decorder
    - dogsled
    - dupl
    - errchkjson
    - errorlint
    - errname
    - exptostd
    - gosec
    - loggercheck
    - misspell
    - musttag
  settings:
    cyclop:
      max-complexity: 15
  exclusions:
    generated: strict
    paths:
      - cmd/mockgw
      - _test.go
formatters:
  enable:
    - gofmt
  exclusions:
    generated: strict
